export const ADD_MEDICINE = 'ADD_MEDICINE'
export const REMOVE_MEDICINE = 'ADD_MEDICINE'
export const ADD_QUANTITY = 'ADD_MEDICINE'
export const REMOVE_QUANTITY = 'ADD_MEDICINE'


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const REMOVE_MEDICINE_MED = 'REMOVE_MEDICINE_MED'
export const ADD_MEDICINE_MED = 'ADD_MEDICINE_MED';
export const MEDICINE_FETCH = 'MEDICINE_FETCH';
export const MEDICINE_FETCH_FAIL = 'MEDICINE_FETCH_FAIL';
export const MEDICINE_FETCH_SUCCESS = 'MEDICINE_FETCH_SUCCESS';
export const MEDIC_FETCH_START= 'MEDIC_FETCH_START';


export const PURCHASE_MEDIC_START = 'PURCHASE_MEDIC_START';